server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true  #是否将自己注册到Eureka Server默认是true
    fetch-registry: true    #是否抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
#      defaultZone: http://localhost:7001/eureka #erueka Server注册中心地址
      defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka